pipeline {
    agent {
    kubernetes {
      inheritFrom 'kubernetesslave'
            yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            some-label: kubernetesslave
        spec:
          serviceAccountName: jenkins-sa
          containers:
          - name: docker-daemon
            image: us-central1-docker.pkg.dev/dev-ops-396910/toorak-repo/java-image-golden:gcp2
            command: ["sleep", "infinity"]
            securityContext:
              runAsUser: 0
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ""
            '''
      
    }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
